/*
 * This file was automatically generated by EvoSuite
 * Thu Sep 24 16:37:55 GMT 2026
 */

package ar.edu.unrc.game2048;

import org.junit.Test;
import static org.junit.Assert.*;
import static org.evosuite.runtime.EvoAssertions.*;
import ar.edu.unrc.game2048.Board;
import ar.edu.unrc.game2048.Cell;
import java.util.Set;
import org.evosuite.runtime.EvoRunner;
import org.evosuite.runtime.EvoRunnerParameters;
import org.junit.runner.RunWith;

@RunWith(EvoRunner.class) @EvoRunnerParameters(mockJVMNonDeterminism = true, useVFS = true, useVNET = true, resetStaticState = true, separateClassLoader = true, useJEE = true) 
public class Board_ESTest extends Board_ESTest_scaffolding {

  @Test(timeout = 4000)
  public void test00()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2048, 2847);
      Board.Position board_Position1 = new Board.Position(2048, (-1730));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertEquals(2048, board_Position1.row);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test01()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-2071), 0);
      Board.Position board_Position1 = new Board.Position(101, 0);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(boolean0);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertEquals(0, board_Position1.col);
  }

  @Test(timeout = 4000)
  public void test02()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(1, 31);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 31) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test03()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(0, 0);
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(cell0.isEmpty());
  }

  @Test(timeout = 4000)
  public void test04()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(2048, 1);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2048, 1) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test05()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveLeft();
      assertFalse(boolean0);
      assertEquals(1, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test06()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveDown();
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
      assertEquals(1, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test07()  throws Throwable  {
      Board board0 = new Board();
      assertEquals(0, board0.getScore());
      
      board0.moveRight();
      int int0 = board0.getScore();
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test08()  throws Throwable  {
      Board board0 = new Board(1);
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOk());
      assertEquals(0, set0.size());
  }

  @Test(timeout = 4000)
  public void test09()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board((Board) null);
        fail("Expecting exception: NullPointerException");
      
      } catch(NullPointerException e) {
         //
         // no message in exception (getMessage() returned null)
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test10()  throws Throwable  {
      Board board0 = new Board(2048);
  }

  @Test(timeout = 4000)
  public void test11()  throws Throwable  {
      Board board0 = new Board(2);
      Board board1 = new Board(board0);
      boolean boolean0 = board1.equals(board0);
      assertTrue(boolean0);
      assertEquals(2, board1.getSize());
      assertFalse(board1.isWinningBoard());
  }

  @Test(timeout = 4000)
  public void test12()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board();
      boolean boolean0 = board0.equals(board1);
      assertEquals(0, board1.getScore());
      assertTrue(board1.repOk());
      assertEquals(4, board1.getSize());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test13()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals(board0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test14()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.hasEmptyCells();
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test15()  throws Throwable  {
      Board board0 = new Board();
      Set<Board.Position> set0 = board0.getEmptyPositions();
      assertTrue(board0.repOk());
      assertEquals(14, set0.size());
  }

  @Test(timeout = 4000)
  public void test16()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(board0);
      board0.moveRight();
      boolean boolean0 = board1.equals(board0);
      assertEquals(4, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test17()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-830), 751);
      Board.Position board_Position1 = new Board.Position((-830), 751);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertTrue(boolean0);
      assertEquals(751, board_Position1.col);
      assertEquals((-830), board_Position1.row);
  }

  @Test(timeout = 4000)
  public void test18()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-2603), (-2603));
      Board.Position board_Position1 = new Board.Position((-2603), 3436);
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertFalse(board_Position1.equals((Object)board_Position0));
      assertFalse(boolean0);
      assertEquals((-2603), board_Position1.row);
  }

  @Test(timeout = 4000)
  public void test19()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2048, 2847);
      Board.Position board_Position1 = new Board.Position(0, (-1730));
      boolean boolean0 = board_Position0.equals(board_Position1);
      assertEquals(2048, board_Position0.row);
      assertEquals((-1730), board_Position1.col);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test20()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(0, 0);
      boolean boolean0 = board_Position0.equals((Object) null);
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test21()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position((-830), 751);
      boolean boolean0 = board_Position0.equals(board_Position0);
      assertEquals((-830), board_Position0.row);
      assertEquals(751, board_Position0.col);
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test22()  throws Throwable  {
      Board board0 = new Board();
      Board.Position board_Position0 = new Board.Position(2, 2048);
      boolean boolean0 = board_Position0.equals(board0);
      assertEquals(2048, board_Position0.col);
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
      assertEquals(2, board_Position0.row);
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test23()  throws Throwable  {
      Board board0 = new Board();
      String string0 = board0.toString();
      assertEquals("Score: 0\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|    2|    2|     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n|     |     |     |     |\n+-----+-----+-----+-----+\n", string0);
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test24()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(2);
      boolean boolean0 = board0.equals(board1);
      assertEquals(2, board1.getSize());
      assertFalse(board1.isWinningBoard());
      assertTrue(board1.repOk());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test25()  throws Throwable  {
      Board board0 = new Board();
      Board.Position board_Position0 = new Board.Position(2, 2048);
      boolean boolean0 = board0.equals(board_Position0);
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
      assertEquals(0, board0.getScore());
      assertEquals(2, board_Position0.row);
      assertFalse(board0.isWinningBoard());
      assertTrue(board0.repOk());
      assertEquals(2048, board_Position0.col);
  }

  @Test(timeout = 4000)
  public void test26()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.equals((Object) null);
      assertEquals(4, board0.getSize());
      assertFalse(boolean0);
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test27()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.repOk();
      assertEquals(0, board0.getScore());
      assertEquals(1, board0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test28()  throws Throwable  {
      Board board0 = new Board();
      Board board1 = new Board(2);
      boolean boolean0 = board1.moveUp();
      boolean boolean1 = board1.moveUp();
      assertFalse(boolean1 == boolean0);
      assertFalse(boolean1);
  }

  @Test(timeout = 4000)
  public void test29()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.moveRight();
      assertEquals(0, board0.getScore());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test30()  throws Throwable  {
      Board board0 = new Board();
      board0.moveLeft();
      boolean boolean0 = board0.repOk();
      assertEquals(4, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test31()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.moveDown();
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
      assertEquals(4, board0.getSize());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test32()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isFull();
      assertTrue(board0.repOk());
      assertTrue(boolean0);
      assertEquals(0, board0.getScore());
  }

  @Test(timeout = 4000)
  public void test33()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isFull();
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertEquals(0, board0.getScore());
      assertFalse(board0.isWinningBoard());
      assertFalse(boolean0);
  }

  @Test(timeout = 4000)
  public void test34()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(board0.repOk());
      assertFalse(boolean0);
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test35()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isWinningBoard();
      assertFalse(boolean0);
      assertEquals(1, board0.getSize());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test36()  throws Throwable  {
      Board board0 = new Board(1);
      boolean boolean0 = board0.isLosingBoard();
      assertTrue(board0.repOk());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test37()  throws Throwable  {
      Board board0 = new Board();
      boolean boolean0 = board0.hasEmptyCells();
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
      assertFalse(board0.isWinningBoard());
      assertEquals(0, board0.getScore());
      assertTrue(boolean0);
  }

  @Test(timeout = 4000)
  public void test38()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(1, 4);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (1, 4) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test39()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.getCell(2, (-1376));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, -1376) is out of bounds for board size 4
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test40()  throws Throwable  {
      Board board0 = new Board(2);
      // Undeclared exception!
      try { 
        board0.setCell(2, 2, (Cell) null);
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (2, 2) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test41()  throws Throwable  {
      Board board0 = new Board(2);
      // Undeclared exception!
      try { 
        board0.getCell((-1178), (-1));
        fail("Expecting exception: IndexOutOfBoundsException");
      
      } catch(IndexOutOfBoundsException e) {
         //
         // Position (-1178, -1) is out of bounds for board size 2
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test42()  throws Throwable  {
      Board board0 = new Board();
      // Undeclared exception!
      try { 
        board0.setCell(2, 2, (Cell) null);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Cell cannot be null
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test43()  throws Throwable  {
      Board board0 = null;
      try {
        board0 = new Board(0);
        fail("Expecting exception: IllegalArgumentException");
      
      } catch(IllegalArgumentException e) {
         //
         // Board size must be positive: 0
         //
         verifyException("ar.edu.unrc.game2048.Board", e);
      }
  }

  @Test(timeout = 4000)
  public void test44()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getSize();
      assertTrue(board0.repOk());
      assertEquals(0, board0.getScore());
      assertEquals(4, int0);
  }

  @Test(timeout = 4000)
  public void test45()  throws Throwable  {
      Board board0 = new Board();
      board0.hashCode();
      assertFalse(board0.isWinningBoard());
      assertEquals(4, board0.getSize());
      assertTrue(board0.repOk());
  }

  @Test(timeout = 4000)
  public void test46()  throws Throwable  {
      Board board0 = new Board();
      int int0 = board0.getScore();
      assertEquals(0, int0);
      assertTrue(board0.repOk());
      assertEquals(4, board0.getSize());
  }

  @Test(timeout = 4000)
  public void test47()  throws Throwable  {
      Board.Position board_Position0 = new Board.Position(2, 2048);
      String string0 = board_Position0.toString();
      assertEquals("(2, 2048)", string0);
  }

  @Test(timeout = 4000)
  public void test48()  throws Throwable  {
      Board board0 = new Board();
      Cell cell0 = board0.getCell(1, 1);
      board0.setCell(0, 2, cell0);
      assertEquals(4, board0.getSize());
      assertEquals(2, cell0.getValue());
  }
}
